server:
  port: 8082

spring:
  datasource:
#    数据库访问配置，使用druid数据源
    druid:
#      数据源mysql
      mysql:
        url: jdbc:mysql:///auth_table?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
#        连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
  #      连接等待时间
  #      spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
  redis:
#    服务器地址
    host: localhost
#     端口
    port: 6379
#    密码
    password:
#      超时时间
    timeout: 2000ms
  swagger:
    enabled: true
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: nsu.littlefish.auth_demo.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
