server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql:///auth_table?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#      spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
  redis:
#    服务器地址
    host: localhost
#     端口
    port: 6379
#    密码
    password:
#      超时时间
    timeout: 2000ms
# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: nsu.littlefish.auth_demo.pojo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
