package nsu.littlefish.authdemo.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table menu_power
 */
public class MenuPower implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_power.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_power.power_id
     *
     * @mbg.generated
     */
    private String powerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu_power.menu_id
     *
     * @mbg.generated
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu_power
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_power.id
     *
     * @return the value of menu_power.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_power.id
     *
     * @param id the value for menu_power.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_power.power_id
     *
     * @return the value of menu_power.power_id
     *
     * @mbg.generated
     */
    public String getPowerId() {
        return powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_power.power_id
     *
     * @param powerId the value for menu_power.power_id
     *
     * @mbg.generated
     */
    public void setPowerId(String powerId) {
        this.powerId = powerId == null ? null : powerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu_power.menu_id
     *
     * @return the value of menu_power.menu_id
     *
     * @mbg.generated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu_power.menu_id
     *
     * @param menuId the value for menu_power.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_power
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", powerId=").append(powerId);
        sb.append(", menuId=").append(menuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}