package nsu.littlefish.authdemo.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table power
 */
public class Power implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.power_id
     *
     * @mbg.generated
     */
    private String powerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power.power_type
     *
     * @mbg.generated
     */
    private String powerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table power
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.power_id
     *
     * @return the value of power.power_id
     *
     * @mbg.generated
     */
    public String getPowerId() {
        return powerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.power_id
     *
     * @param powerId the value for power.power_id
     *
     * @mbg.generated
     */
    public void setPowerId(String powerId) {
        this.powerId = powerId == null ? null : powerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power.power_type
     *
     * @return the value of power.power_type
     *
     * @mbg.generated
     */
    public String getPowerType() {
        return powerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power.power_type
     *
     * @param powerType the value for power.power_type
     *
     * @mbg.generated
     */
    public void setPowerType(String powerType) {
        this.powerType = powerType == null ? null : powerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", powerId=").append(powerId);
        sb.append(", powerType=").append(powerType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}