package nsu.littlefish.authdemo.mapper;

import nsu.littlefish.authdemo.pojo.Power;
import org.springframework.stereotype.Repository;

@Repository
public interface PowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String powerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int insert(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int insertSelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    Power selectByPrimaryKey(String powerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Power record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Power record);
}
