package nsu.littlefish.authdemo.mapper;

import nsu.littlefish.authdemo.pojo.RolePower;
import org.springframework.stereotype.Repository;

@Repository
public interface RolePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbg.generated
     */
    int insert(RolePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbg.generated
     */
    int insertSelective(RolePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbg.generated
     */
    RolePower selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RolePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_power
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolePower record);
}
