package nsu.littlefish.authdemo.mapper;

import nsu.littlefish.authdemo.pojo.User;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface UserMapper {
    /**
     * 根据名字查询用户
     * @param userName
     * @throws Exception
     * @return
     */
    User getUserByUserName(@Param(value = "userName") String userName) throws Exception;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @throws Exception
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @throws Exception
     * @mbg.generated
     */
    int insert(User record) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @throws Exception
     * @mbg.generated
     */
    int insertSelective(User record) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @throws Exception
     * @mbg.generated
     */
    User selectByPrimaryKey(String userId) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @throws Exception
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @throws Exception
     * @mbg.generated
     */
    int updateByPrimaryKey(User record) throws Exception;
}
